import React from "react";
// import { QuestionMarkCircleIcon } from "@heroicons/react/outline";

import {
    Pin,
    Help,
    Call,
    Card,
    Chat,
    Close,
    OpenWindow,
    Share,
    Stats,
    TeddraLogo,
    Viewer,
    HomeIcon,
    FilterIcon,
    Document,
    FlagIcon,
    GroupBy,
    Degroup,
    Miniature,
    Zoom,
    Print,
    UserIcon,
    MinuatureTab,
    Globe,
    Entreprise,
    List,
    Thumbnails,
    Blocks,
    Search,
    PlusIcon,
    Unpin,
    AddDocument,
    News,
    Shortcut,
    PanelClose, 
    PanelOpen,
    TwoLines,
    Modes,
    LocalTree,
    Calendar, 
    ChevronDownIcon,
    XCircleIcon,
    Favorites,
    Broadcast, 
    CommercialTree, 
    ModeUrl,
    MoreInfo,
    TeddraLogoSelected,
    SearchByType,
    SearchByRegion,
    Server,
    Datacenter,
    Notification, 
    OneLine,
    Manage,
    Publish,
    AddLocation,
    Legal,
    Unshortcut,
    Warning

} from "./index";
import { IconOptions } from "../../types";
type ComponentOptions = {
  [key: string]: React.ElementType
}
const Components : ComponentOptions = {
  Pin,
  Help,
  Call,
  Card,
  Chat,
  Close,
  OpenWindow,
  Share,
  Stats,
  TeddraLogo,
  Viewer,
  HomeIcon,
  FilterIcon,
  Document,
  FlagIcon,
  GroupBy,
  Degroup,
  Miniature,
  Zoom,
  Print,
  UserIcon,
  MinuatureTab,
  Globe,
  Entreprise,
  List,
  Thumbnails,
  Blocks,
  Search,
  PlusIcon,
  Unpin,
  AddDocument,
  News,
  Shortcut,
  PanelClose, 
  PanelOpen,
  TwoLines,
  Modes,
  LocalTree,
  Calendar, 
  ChevronDownIcon,
  XCircleIcon,
  Favorites,
  Broadcast, 
  CommercialTree, 
  ModeUrl,
  MoreInfo,
  TeddraLogoSelected,
  SearchByType,
  SearchByRegion,
  Server,
  Datacenter,
  Notification, 
  OneLine,
  Manage,
  Publish,
  AddLocation,
  Legal,
  Unshortcut,
  Warning


};

export default function Icon({ name, className, style } : IconOptions) {
  if (typeof (Components as any)[name ? name : ''] != "undefined") {
    return React.createElement((Components as any)[name ? name : ''], {
      className: className,
      style: style?style:{}
    });
  }

  return <div></div>;
}
